### ISSUE TITLE
Viaje plus

### ISSUE THREAD

**Issue by pabloantuna** [pabloantuna/TrabajoTarjeta-AAT-Antuna-Bachur#1]
- Si la tarjeta se queda sin crédito, puede otorgar hasta dos viajes plus.
- Cuando se vuelve a cargar la tarjeta, se descuenta el saldo de lo que se haya
- consumido en concepto de viaje plus.
- Escribir un test que valide que se pueden dar hasta dos viajes plus.
- Escribir un test que valide que el saldo de la tarjeta descuenta correctamente el/los viaje/s plus otorgado/s.

**Comment by pabloantuna** [comment]
Realizada implementación solicitada, falta revisión para ver si cambiamos algo de la misma

**Comment by LucasBachur** [comment]
Revisado

**Comment by pabloantuna** [comment]
Se cierra issue por ser completado
